# Role for managing pods, exec/logs, and restarting workloads in dev namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: dev
  name: pod-manager-role
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods/exec", "pods/log"]
    verbs: ["get", "create"]
  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets"]
    verbs: ["get", "list", "watch", "patch"]

---

# RoleBinding for managing pods and workloads in dev namespace for all developers
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: dev
  name: pod-manager-binding
subjects:
  - kind: User
    name: akhil
    apiGroup: rbac.authorization.k8s.io
  - kind: User
    name: anish
    apiGroup: rbac.authorization.k8s.io
  - kind: User
    name: bpradipta
    apiGroup: rbac.authorization.k8s.io
