apiVersion: v1
kind: Namespace
metadata:
  name: dev-akhil

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: dev-akhil
  name: dev-admin-role
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: dev-akhil
  name: dev-admin-binding
subjects:
  - kind: User
    name: akhil
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: dev-admin-role
  apiGroup: rbac.authorization.k8s.io
---

# Developer Anish 
apiVersion: v1
kind: Namespace
metadata:
  name: dev-anish

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: dev-anish
  name: dev-admin-role
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: dev-anish
  name: dev-admin-binding
subjects:
  - kind: User
    name: anish
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: dev-admin-role
  apiGroup: rbac.authorization.k8s.io

---
# Developer bpradipta 
apiVersion: v1
kind: Namespace
metadata:
  name: dev-bpradipta

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: dev-bpradipta
  name: dev-admin-role
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: dev-bpradipta
  name: dev-admin-binding
subjects:
  - kind: User
    name: bpradipta
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: dev-admin-role
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: dev-admin-role
  apiGroup: rbac.authorization.k8s.io
---